[package]
authors = ["C J Silverio <ceejceej@gmail.com>", "Chris Dickinson <chris@neversaw.us>"]
edition = "2018"
name = "ludwig"
version = "0.1.0"
[dependencies]
anyhow = "1.0.31"
lazy_static = "1.4.0"
ron = "0.6.0"
serde = "1.0.110"
structopt = "0.3.14"
subprocess = "*"
tera = "1.3.0"
