[package]
name = "ludwig"
version = "0.1.0"
authors = ["C J Silverio <ceejceej@gmail.com>", "Chris Dickinson <chris@neversaw.us>"]
edition = "2018"

[dependencies]
tera = "1.3.0"
structopt = "0.3.14"
lazy_static = "1.4.0"
anyhow = "1.0.31"
ron = "0.6.0"
serde = "1.0.110"
