name: build container artifacts
on:
  push:
    branches:
      - 'deploy/*'
jobs:

  docker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --build-arg GIT_COMMIT_IN=$(git rev-parse --short HEAD) \
          --tag ${GITHUB_REPOSITORY#*/}:$(node -pe 'require("./package").version')-$(git rev-parse --short HEAD)
        
